from typing import Any, TypedDict


class AnalystState(TypedDict, total=False):
    # Original user question
    question: str

    # Database schema provided to the agent
    schema: str

    # SQL generated by Gemini
    sql: str

    # SQL validation information
    is_valid: bool
    validation_message: str

    # Database query result
    columns: list[str]
    rows: list[dict[str, Any]]

    # AI analysis of the query result
    analysis: str

    # Visualization information
    visualization: dict[str, Any]

    # Final response shown to the user
    final_response: str

    # Error information
    error: str


        # Structured interpretation of the question
    intent: str
    metric: str
    dimension: str
    filters: list[str]
    time_range: str